CREATE TYPE "XpEventType" AS ENUM (
  'MESSAGE_SENT',
  'MESSAGE_REPLY',
  'FRIEND_ACCEPTED',
  'JOIN_REQUEST_CREATED',
  'JOIN_REQUEST_ACCEPTED',
  'HOST_LOBBY_CREATED',
  'LOBBY_ACTIVE_20_MIN'
);

ALTER TABLE "User" ADD COLUMN "xpTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "xpThisLevel" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "lastXpAt" TIMESTAMP(3);

CREATE TABLE "XpEvent" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "XpEventType" NOT NULL,
    "amount" INTEGER NOT NULL,
    "meta" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "XpEvent_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "XpEvent" ADD CONSTRAINT "XpEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "xp_events_user_created_idx" ON "XpEvent"("userId", "createdAt");
